### ISSUE TITLE
Getting error at the end of installation

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh-cs#1]
Ran command: sudo apt-get install nosh-cs

  [Illuminate\Database\QueryException]  
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `curr_textdefinition_f` add index curr_textdefinition_f_term_index(`term`))

**Comment by shihjay2** [comment]
This might be due to an issue with the default collation for your mysql
database; make sure it is utf8_general_ci in your mysql settings.

**Comment by ajinkyagadewar** [comment]
It solved the problem but got another error:

Installed NOSH ChartingSystem core files.
cp: cannot stat '/var/www/oldnosh/images/*': No such file or directory
dpkg: error processing package nosh-cs (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.19-0ubuntu6) ...
Errors were encountered while processing:
 nosh-cs
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by shihjay2** [comment]
It appears that you tried to repeat the install command on top of a failed
initial install of nosh.  This is triggering an update command which will
cause this error since the previous install failed.

sudo apt-get remove nosh-cs

Then make sure you delete your /noshdocuments directory (or whichever
directory to designated as the NOSH documents folder)
sudo rm -rf /noshdocuments

Then delete the nosh database in mysql
mysql -u <username> -p<password>
DROP DATABASE IF EXISTS nosh;
exit;

Then re-install nosh
sudo apt-get install nosh-cs

**Comment by ajinkyagadewar** [comment]
Even remove is giving me error:

# sudo apt-get remove nosh-cs

Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libapache2-mod-php5 libgcrypt11-dev libgpg-error-dev libssh2-1 libssh2-1-dev
  libssh2-php mysql-server php-auth-sasl php-http-request php-mail
  php-mail-mime php-net-dime php-net-smtp php-net-socket php-net-url php-soap
  php5 php5-mysql php5-ssh2
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  nosh-cs
0 upgraded, 0 newly installed, 1 to remove and 181 not upgraded.
After this operation, 54.3 kB disk space will be freed.
Do you want to continue? [Y/n](Reading database ... 72492 files and directories currently installed.)
Removing nosh-cs (1.8.1-0ubuntu10) ...
Removed NOSH ChartingSystem supplemental files.
dpkg: error processing package nosh-cs (--remove):
 subprocess installed pre-removal script returned error exit status 1
Errors were encountered while processing:
 nosh-cs
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by shihjay2** [comment]
Suggest trying:
sudo dpkg --remove --force-remove-reinstreq nosh-cs

**Comment by ajinkyagadewar** [comment]
# sudo dpkg --remove --force-remove-reinstreq nosh-cs

(Reading database ... 72492 files and directories currently installed.)
Removing nosh-cs (1.8.1-0ubuntu10) ...
Removed NOSH ChartingSystem supplemental files.
dpkg: error processing package nosh-cs (--remove):
 subprocess installed pre-removal script returned error exit status 1
Errors were encountered while processing:
 nosh-cs

**Comment by shihjay2** [comment]
Have you tried sudo apt-get install -f first and then sudo apt-get install
nosh-cs?

**Comment by ajinkyagadewar** [comment]
No. I have followed the steps mentioned on https://github.com/shihjay2/nosh-cs/wiki/Installation#ubuntu-ppa.
1. sudo add-apt-repository ppa:shihjay2/nosh-chartingsystem
2. sudo apt-get update
3. sudo apt-get install nosh-cs

**Comment by shihjay2** [comment]
I think you misunderstood my directive;
Use the commands

sudo apt-get install -f
sudo apt-get update
sudo apt-get install nosh-cs

to see if it will fix and remove the broken installation.
If that doesn't work, then try this

sudo mv /var/lib/dpkg/info/nosh-cs.\* /tmp/
sudo dpkg --remove --force-remove-reinstreq nosh-cs

**Comment by ajinkyagadewar** [comment]
Nothing is working. I tried everything on a fresh virtual machine.

Installation Error:
knplabs/github-api suggests installing knplabs/gaufrette (Needed for optional Gaufrette cache)
Generating autoload files

> php artisan clear-compiled
> php artisan optimize
> Generating optimized class loader
> php artisan key:generate
> Application key [UGYkCUVsYPML4LbrgEwtmFozEYe85B3f] set successfully.
> Installed NOSH ChartingSystem core files.
> cp: cannot stat '/var/www/oldnosh/images/*': No such file or directory
> dpkg: error processing package nosh-cs (--configure):
>  subprocess installed post-installation script returned error exit status 1
> Processing triggers for libc-bin (2.19-0ubuntu6) ...
> Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.30.7-0ubuntu1) ...
> Errors were encountered while processing:
>  nosh-cs

[10:50 AM]-[root@phr]-[/home/vagrant] 

# sudo apt-get install nosh-cs

Reading package lists... Done
Building dependency tree  
Reading state information... Done
nosh-cs is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 181 not upgraded.

[10:52 AM]-[root@phr]-[/home/vagrant] 

# sudo mv /var/lib/dpkg/info/nosh-cs.\* /tmp/

[10:52 AM]-[root@phr]-[/home/vagrant] 

# sudo dpkg --remove --force-remove-reinstreq nosh-cs

dpkg: warning: files list file for package 'nosh-cs' missing; assuming package has no files currently installed
(Reading database ... 72485 files and directories currently installed.)
Removing nosh-cs (1.8.1-0ubuntu10) ...

**Comment by shihjay2** [comment]
Looking at the timing of your commands above and the response; it appears
that you have successfully removed nosh-cs.

Just to make sure there are no remnants of nosh-cs prior to re-install,
here are the next steps
sudo composer clear-cache
sudo rm -rf /noshdocuments
mysql -u <username> -p<password>
DROP DATABASE nosh;
sudo apt-get update
sudo apt-get install nosh-cs

**Comment by shihjay2** [comment]
BTW, I ran through a uninstall -> install process on a test machine just
now and there are no errors; it looks like in your process got stalled when
it first encountered a database install error and then you tried to
re-install again without fully clearing the database and associated files
and it was stuck.  Please try again.

**Comment by ajinkyagadewar** [comment]
Finally it worked :+1: 

Everything failed on vagrant setup but I purchased a vps instance and tried to run the setup and it worked smoothly. 
Thanks for the help.
