### ISSUE TITLE
Error on installing as a Medical practice

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh-cs#2]
Ajax Error: Undefined Variable display_name. 

It comes when we submit the form for installation.

**Comment by shihjay2** [comment]
There is a small bug that you have identified.  The settings have been
saved so if you point to https://<ip address of server>/nosh
you'll be logged in (or it'll point to the login page) for the
administrator and you can proceed from there.

I'll be pushing an update soon.

Michael

**Comment by ajinkyagadewar** [comment]
Working now
