### ISSUE TITLE
US Focused Project

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh-cs#3]
Seems Nosh is US focused project as there in no country selection. Do you plan to extend the functionality for other countries too?

**Comment by shihjay2** [comment]
Unfortunately, I only have time and resources to focus on the US (I'm so
far the only one coding this project at the moment).  If anyone is willing
to help to extend it to other countries, I'm open to have pull requests
into the project for internationalization.

**Comment by ajinkyagadewar** [comment]
Me and my team would like to work on this project.

**Comment by shihjay2** [comment]
Thanks!
