### ISSUE TITLE
Integration with wordpress

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh-cs#4]
Is there any way to integrate nosh with wordpress site for seamless authentication?

**Comment by shihjay2** [comment]
I don't understand the question - which authentication method with
wordpress are you referring to (? login to wordpress site, single sign-on?)

**Comment by ajinkyagadewar** [comment]
Yes. Do you have a skype id?

**Comment by shihjay2** [comment]
I'm working on a single-sign-on feature coupled with another project -
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server; it's
in testing right now and I'm building a federated identity server that acts
as the single sign on for physicians - I do not plan on using other oauth
identity servers such as Google, Facebook, Twitter at this time.

My Skype ID is shihjay2.

**Comment by ajinkyagadewar** [comment]
Sent you the Skype request.

**Comment by shihjay2** [comment]
Thanks, I'll get back to you about it tomorrow; end of the day for me...

**Comment by ajinkyagadewar** [comment]
Sure.
